apiVersion: tor.stack.io/v1beta1
kind: TorBridgeConfig
metadata:
  name: torbridgeconfig-sample
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
spec:
  image: dperson/torproxy
  orPort: 9001
  dirPort: 9030
  socksPort: 9050
  onionServiceDir: /var/lib/tor/onion_service/
  onionServicePort: 80
  onionServiceTarget: 127.0.0.1:80