//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExitNode) DeepCopyInto(out *ExitNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExitNode.
func (in *ExitNode) DeepCopy() *ExitNode {
	if in == nil {
		return nil
	}
	out := new(ExitNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiddenService) DeepCopyInto(out *HiddenService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiddenService.
func (in *HiddenService) DeepCopy() *HiddenService {
	if in == nil {
		return nil
	}
	out := new(HiddenService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkConfig) DeepCopyInto(out *TorNetworkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkConfig.
func (in *TorNetworkConfig) DeepCopy() *TorNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(TorNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorNetworkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkConfigList) DeepCopyInto(out *TorNetworkConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TorNetworkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkConfigList.
func (in *TorNetworkConfigList) DeepCopy() *TorNetworkConfigList {
	if in == nil {
		return nil
	}
	out := new(TorNetworkConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorNetworkConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkConfigSpec) DeepCopyInto(out *TorNetworkConfigSpec) {
	*out = *in
	if in.DefaultExitNodes != nil {
		in, out := &in.DefaultExitNodes, &out.DefaultExitNodes
		*out = make([]ExitNode, len(*in))
		copy(*out, *in)
	}
	if in.HiddenServices != nil {
		in, out := &in.HiddenServices, &out.HiddenServices
		*out = make([]HiddenService, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkConfigSpec.
func (in *TorNetworkConfigSpec) DeepCopy() *TorNetworkConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TorNetworkConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkConfigStatus) DeepCopyInto(out *TorNetworkConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkConfigStatus.
func (in *TorNetworkConfigStatus) DeepCopy() *TorNetworkConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TorNetworkConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkSidecarControllerConfig) DeepCopyInto(out *TorNetworkSidecarControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkSidecarControllerConfig.
func (in *TorNetworkSidecarControllerConfig) DeepCopy() *TorNetworkSidecarControllerConfig {
	if in == nil {
		return nil
	}
	out := new(TorNetworkSidecarControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorNetworkSidecarControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkSidecarControllerConfigList) DeepCopyInto(out *TorNetworkSidecarControllerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TorNetworkSidecarControllerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkSidecarControllerConfigList.
func (in *TorNetworkSidecarControllerConfigList) DeepCopy() *TorNetworkSidecarControllerConfigList {
	if in == nil {
		return nil
	}
	out := new(TorNetworkSidecarControllerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorNetworkSidecarControllerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkSidecarControllerConfigSpec) DeepCopyInto(out *TorNetworkSidecarControllerConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkSidecarControllerConfigSpec.
func (in *TorNetworkSidecarControllerConfigSpec) DeepCopy() *TorNetworkSidecarControllerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TorNetworkSidecarControllerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorNetworkSidecarControllerConfigStatus) DeepCopyInto(out *TorNetworkSidecarControllerConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorNetworkSidecarControllerConfigStatus.
func (in *TorNetworkSidecarControllerConfigStatus) DeepCopy() *TorNetworkSidecarControllerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TorNetworkSidecarControllerConfigStatus)
	in.DeepCopyInto(out)
	return out
}
